services:
  postgres:
    build: ./docker
    image: sample-db
    container_name: sample-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - sample-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    restart: always

volumes:
  sample-data:
    driver: local
